require("dein")

require("base")
require("keymap")
require("tab")

require("plugins/devicons")
require("plugins/molokai")
require("plugins/lualine")
require("plugins/lspconfig")
require("plugins/nvim_cmp")
require("plugins/mason")
require("plugins/linter")
require("plugins/fern")
require("plugins/chowcho")
require("plugins/neoscroll")
require("plugins/telescope")
require("plugins/whichkey")
require("plugins/noice")
require("plugins/indentline")
require("plugins/gitsigns")
require("plugins/toggleterm")
require('plugins/illuminate')

